// ============================================================
// FINMATRIX - Audit Trail Dummy Data (30 entries)
// ============================================================

export type AuditAction = 'create' | 'update' | 'delete';

export type AuditModule =
  | 'invoices'
  | 'inventory'
  | 'customers'
  | 'vendors'
  | 'bills'
  | 'banking'
  | 'employees'
  | 'payroll'
  | 'settings'
  | 'journal_entries'
  | 'delivery';

export interface AuditEntry {
  id: string;
  userId: string;
  userName: string;
  action: AuditAction;
  module: AuditModule;
  recordId: string;
  description: string;
  oldValue: string | null;
  newValue: string | null;
  timestamp: string;
}

export const auditTrail: AuditEntry[] = [
  {
    id: 'aud_001',
    userId: 'usr_001',
    userName: 'Alex Morgan',
    action: 'create',
    module: 'invoices',
    recordId: 'inv_020',
    description: 'Created Invoice INV-1020',
    oldValue: null,
    newValue: '{"invoiceNumber":"INV-1020","customer":"Acme Corp","total":4250.00}',
    timestamp: '2026-03-03T14:30:00Z',
  },
  {
    id: 'aud_002',
    userId: 'usr_002',
    userName: 'Sarah Chen',
    action: 'update',
    module: 'inventory',
    recordId: 'item_004',
    description: 'Updated quantity for Widget Pro X',
    oldValue: '{"quantityOnHand":15}',
    newValue: '{"quantityOnHand":3}',
    timestamp: '2026-03-03T13:15:00Z',
  },
  {
    id: 'aud_003',
    userId: 'usr_001',
    userName: 'Alex Morgan',
    action: 'update',
    module: 'customers',
    recordId: 'cust_003',
    description: 'Updated Riverstone LLC credit limit',
    oldValue: '{"creditLimit":10000}',
    newValue: '{"creditLimit":15000}',
    timestamp: '2026-03-03T11:45:00Z',
  },
  {
    id: 'aud_004',
    userId: 'usr_003',
    userName: 'James Wilson',
    action: 'create',
    module: 'bills',
    recordId: 'bill_016',
    description: 'Created Bill BILL-1016 from Pacific Supply',
    oldValue: null,
    newValue: '{"billNumber":"BILL-1016","vendor":"Pacific Supply Co","total":2180.00}',
    timestamp: '2026-03-03T10:00:00Z',
  },
  {
    id: 'aud_005',
    userId: 'usr_001',
    userName: 'Alex Morgan',
    action: 'update',
    module: 'invoices',
    recordId: 'inv_005',
    description: 'Marked Invoice INV-1005 as overdue',
    oldValue: '{"status":"sent"}',
    newValue: '{"status":"overdue"}',
    timestamp: '2026-03-03T09:00:00Z',
  },
  {
    id: 'aud_006',
    userId: 'usr_002',
    userName: 'Sarah Chen',
    action: 'create',
    module: 'journal_entries',
    recordId: 'je_045',
    description: 'Created Journal Entry JE-045 — Depreciation',
    oldValue: null,
    newValue: '{"entryNumber":"JE-045","description":"Monthly depreciation","amount":1200}',
    timestamp: '2026-03-02T16:30:00Z',
  },
  {
    id: 'aud_007',
    userId: 'usr_001',
    userName: 'Alex Morgan',
    action: 'update',
    module: 'banking',
    recordId: 'txn_091',
    description: 'Reconciled bank transaction TXN-091',
    oldValue: '{"reconciled":false}',
    newValue: '{"reconciled":true}',
    timestamp: '2026-03-02T15:00:00Z',
  },
  {
    id: 'aud_008',
    userId: 'usr_003',
    userName: 'James Wilson',
    action: 'delete',
    module: 'invoices',
    recordId: 'inv_018',
    description: 'Deleted draft Invoice INV-1018',
    oldValue: '{"invoiceNumber":"INV-1018","status":"draft","total":780}',
    newValue: null,
    timestamp: '2026-03-02T14:00:00Z',
  },
  {
    id: 'aud_009',
    userId: 'usr_002',
    userName: 'Sarah Chen',
    action: 'create',
    module: 'customers',
    recordId: 'cust_021',
    description: 'Created Customer BrightStar Inc',
    oldValue: null,
    newValue: '{"name":"BrightStar Inc","email":"info@brightstar.io"}',
    timestamp: '2026-03-02T11:20:00Z',
  },
  {
    id: 'aud_010',
    userId: 'usr_001',
    userName: 'Alex Morgan',
    action: 'update',
    module: 'employees',
    recordId: 'emp_005',
    description: 'Updated salary for Marcus Lee',
    oldValue: '{"annualSalary":62000}',
    newValue: '{"annualSalary":68000}',
    timestamp: '2026-03-02T10:00:00Z',
  },
  {
    id: 'aud_011',
    userId: 'usr_003',
    userName: 'James Wilson',
    action: 'create',
    module: 'vendors',
    recordId: 'ven_012',
    description: 'Created Vendor Pacific Supply Co',
    oldValue: null,
    newValue: '{"companyName":"Pacific Supply Co","contactPerson":"Rita Lee"}',
    timestamp: '2026-03-01T16:45:00Z',
  },
  {
    id: 'aud_012',
    userId: 'usr_001',
    userName: 'Alex Morgan',
    action: 'update',
    module: 'inventory',
    recordId: 'item_009',
    description: 'Adjusted Copper Wire Spool stock',
    oldValue: '{"quantityOnHand":25}',
    newValue: '{"quantityOnHand":5}',
    timestamp: '2026-03-01T14:30:00Z',
  },
  {
    id: 'aud_013',
    userId: 'usr_002',
    userName: 'Sarah Chen',
    action: 'update',
    module: 'invoices',
    recordId: 'inv_002',
    description: 'Recorded payment for INV-1002',
    oldValue: '{"amountPaid":0,"status":"sent"}',
    newValue: '{"amountPaid":8200,"status":"paid"}',
    timestamp: '2026-03-01T11:00:00Z',
  },
  {
    id: 'aud_014',
    userId: 'usr_001',
    userName: 'Alex Morgan',
    action: 'create',
    module: 'payroll',
    recordId: 'pr_feb_2026',
    description: 'Processed February 2026 payroll',
    oldValue: null,
    newValue: '{"period":"February 2026","employees":8,"total":34500}',
    timestamp: '2026-02-28T16:00:00Z',
  },
  {
    id: 'aud_015',
    userId: 'usr_003',
    userName: 'James Wilson',
    action: 'delete',
    module: 'vendors',
    recordId: 'ven_008',
    description: 'Deactivated Vendor QuickParts Ltd',
    oldValue: '{"isActive":true}',
    newValue: '{"isActive":false}',
    timestamp: '2026-02-28T10:30:00Z',
  },
  {
    id: 'aud_016',
    userId: 'usr_002',
    userName: 'Sarah Chen',
    action: 'update',
    module: 'settings',
    recordId: 'settings_001',
    description: 'Updated company tax ID',
    oldValue: '{"taxId":"12-3456780"}',
    newValue: '{"taxId":"12-3456789"}',
    timestamp: '2026-02-27T14:15:00Z',
  },
  {
    id: 'aud_017',
    userId: 'usr_001',
    userName: 'Alex Morgan',
    action: 'create',
    module: 'invoices',
    recordId: 'inv_015',
    description: 'Created Invoice INV-1015',
    oldValue: null,
    newValue: '{"invoiceNumber":"INV-1015","customer":"Greenfield Farms","total":2400}',
    timestamp: '2026-02-27T11:00:00Z',
  },
  {
    id: 'aud_018',
    userId: 'usr_003',
    userName: 'James Wilson',
    action: 'update',
    module: 'bills',
    recordId: 'bill_010',
    description: 'Paid Bill BILL-1010 via bank transfer',
    oldValue: '{"status":"received","amountPaid":0}',
    newValue: '{"status":"paid","amountPaid":3200}',
    timestamp: '2026-02-26T15:45:00Z',
  },
  {
    id: 'aud_019',
    userId: 'usr_002',
    userName: 'Sarah Chen',
    action: 'create',
    module: 'inventory',
    recordId: 'item_020',
    description: 'Added new item Industrial Glue Tubes',
    oldValue: null,
    newValue: '{"sku":"IGT-300","name":"Industrial Glue Tubes","category":"supplies"}',
    timestamp: '2026-02-26T09:30:00Z',
  },
  {
    id: 'aud_020',
    userId: 'usr_001',
    userName: 'Alex Morgan',
    action: 'update',
    module: 'customers',
    recordId: 'cust_001',
    description: 'Updated Acme Corp shipping address',
    oldValue: '{"shippingAddress":"100 Main St"}',
    newValue: '{"shippingAddress":"200 Commerce Blvd"}',
    timestamp: '2026-02-25T13:00:00Z',
  },
  {
    id: 'aud_021',
    userId: 'usr_003',
    userName: 'James Wilson',
    action: 'delete',
    module: 'journal_entries',
    recordId: 'je_039',
    description: 'Voided Journal Entry JE-039',
    oldValue: '{"entryNumber":"JE-039","status":"posted"}',
    newValue: '{"entryNumber":"JE-039","status":"voided"}',
    timestamp: '2026-02-25T10:00:00Z',
  },
  {
    id: 'aud_022',
    userId: 'usr_002',
    userName: 'Sarah Chen',
    action: 'create',
    module: 'employees',
    recordId: 'emp_009',
    description: 'Added Employee Priya Patel',
    oldValue: null,
    newValue: '{"name":"Priya Patel","department":"Finance","salary":55000}',
    timestamp: '2026-02-24T14:30:00Z',
  },
  {
    id: 'aud_023',
    userId: 'usr_001',
    userName: 'Alex Morgan',
    action: 'update',
    module: 'banking',
    recordId: 'acc_002',
    description: 'Updated Checking Account opening balance',
    oldValue: '{"openingBalance":50000}',
    newValue: '{"openingBalance":52500}',
    timestamp: '2026-02-24T09:15:00Z',
  },
  {
    id: 'aud_024',
    userId: 'usr_003',
    userName: 'James Wilson',
    action: 'create',
    module: 'bills',
    recordId: 'bill_014',
    description: 'Created Bill BILL-1014 from Steel World Inc',
    oldValue: null,
    newValue: '{"billNumber":"BILL-1014","vendor":"Steel World Inc","total":4600}',
    timestamp: '2026-02-22T16:00:00Z',
  },
  {
    id: 'aud_025',
    userId: 'usr_001',
    userName: 'Alex Morgan',
    action: 'update',
    module: 'invoices',
    recordId: 'inv_010',
    description: 'Sent Invoice INV-1010 to customer',
    oldValue: '{"status":"draft"}',
    newValue: '{"status":"sent"}',
    timestamp: '2026-02-22T11:30:00Z',
  },
  {
    id: 'aud_026',
    userId: 'usr_002',
    userName: 'Sarah Chen',
    action: 'update',
    module: 'inventory',
    recordId: 'item_002',
    description: 'Received 50 units of Aluminum Sheets',
    oldValue: '{"quantityOnHand":30}',
    newValue: '{"quantityOnHand":80}',
    timestamp: '2026-02-21T10:00:00Z',
  },
  {
    id: 'aud_027',
    userId: 'usr_001',
    userName: 'Alex Morgan',
    action: 'delete',
    module: 'customers',
    recordId: 'cust_019',
    description: 'Deactivated Customer OldTech Solutions',
    oldValue: '{"isActive":true}',
    newValue: '{"isActive":false}',
    timestamp: '2026-02-20T14:45:00Z',
  },
  {
    id: 'aud_028',
    userId: 'usr_003',
    userName: 'James Wilson',
    action: 'create',
    module: 'invoices',
    recordId: 'inv_012',
    description: 'Created Invoice INV-1012',
    oldValue: null,
    newValue: '{"invoiceNumber":"INV-1012","customer":"TechWave Solutions","total":5300}',
    timestamp: '2026-02-19T11:00:00Z',
  },
  {
    id: 'aud_029',
    userId: 'usr_002',
    userName: 'Sarah Chen',
    action: 'update',
    module: 'payroll',
    recordId: 'emp_003',
    description: 'Updated tax withholding for Lisa Park',
    oldValue: '{"federalWithholding":15}',
    newValue: '{"federalWithholding":18}',
    timestamp: '2026-02-18T09:30:00Z',
  },
  {
    id: 'aud_030',
    userId: 'usr_001',
    userName: 'Alex Morgan',
    action: 'create',
    module: 'banking',
    recordId: 'txn_085',
    description: 'Recorded bank deposit TXN-085 ($12,500)',
    oldValue: null,
    newValue: '{"type":"deposit","amount":12500,"account":"Checking"}',
    timestamp: '2026-02-17T15:00:00Z',
  },
];
