// ============================================================
// FINMATRIX - Bank Transactions Dummy Data (50 Transactions)
// ============================================================

export type BankTxType = 'check' | 'deposit' | 'transfer' | 'card_charge' | 'fee' | 'interest';

export interface BankTransaction {
  txId: string;
  bankAccountId: string;
  date: string;
  payee: string;
  description: string;
  type: BankTxType;
  amount: number; // negative = payment, positive = deposit
  checkNumber: string | null;
  category: string;
  accountId: string; // COA account
  isCleared: boolean;
  isReconciled: boolean;
  referenceNumber: string;
}

export const bankTransactions: BankTransaction[] = [
  // ─── BUSINESS CHECKING (bank_001) ── 30 transactions ─────
  {
    txId: 'btx_001',
    bankAccountId: 'bank_001',
    date: '2026-01-05',
    payee: 'ABC Property Management',
    description: 'January office rent',
    type: 'check',
    amount: -4500,
    checkNumber: '1001',
    category: 'Rent',
    accountId: 'acc_023',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'CHK-1001',
  },
  {
    txId: 'btx_002',
    bankAccountId: 'bank_001',
    date: '2026-01-08',
    payee: 'Acme Corporation',
    description: 'Invoice #INV-001 payment received',
    type: 'deposit',
    amount: 8500,
    checkNumber: null,
    category: 'Sales Revenue',
    accountId: 'acc_017',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'DEP-2001',
  },
  {
    txId: 'btx_003',
    bankAccountId: 'bank_001',
    date: '2026-01-10',
    payee: 'City Power & Light',
    description: 'January electricity bill',
    type: 'check',
    amount: -340,
    checkNumber: '1002',
    category: 'Utilities',
    accountId: 'acc_024',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'CHK-1002',
  },
  {
    txId: 'btx_004',
    bankAccountId: 'bank_001',
    date: '2026-01-12',
    payee: 'Payroll - Week 1',
    description: 'Employee payroll disbursement',
    type: 'check',
    amount: -7600,
    checkNumber: '1003',
    category: 'Salaries',
    accountId: 'acc_025',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'CHK-1003',
  },
  {
    txId: 'btx_005',
    bankAccountId: 'bank_001',
    date: '2026-01-15',
    payee: 'TechVentures LLC',
    description: 'Consulting services payment',
    type: 'deposit',
    amount: 5200,
    checkNumber: null,
    category: 'Service Revenue',
    accountId: 'acc_018',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'DEP-2002',
  },
  {
    txId: 'btx_006',
    bankAccountId: 'bank_001',
    date: '2026-01-17',
    payee: 'Office Depot',
    description: 'Office supplies - paper & toner',
    type: 'check',
    amount: -285,
    checkNumber: '1004',
    category: 'Office Supplies',
    accountId: 'acc_026',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'CHK-1004',
  },
  {
    txId: 'btx_007',
    bankAccountId: 'bank_001',
    date: '2026-01-20',
    payee: 'Transfer to Savings',
    description: 'Monthly savings transfer',
    type: 'transfer',
    amount: -3000,
    checkNumber: null,
    category: 'Transfer',
    accountId: 'acc_003',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'TRF-3001',
  },
  {
    txId: 'btx_008',
    bankAccountId: 'bank_001',
    date: '2026-01-22',
    payee: 'Global Parts Inc',
    description: 'Inventory purchase payment',
    type: 'check',
    amount: -2150,
    checkNumber: '1005',
    category: 'Cost of Goods Sold',
    accountId: 'acc_021',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'CHK-1005',
  },
  {
    txId: 'btx_009',
    bankAccountId: 'bank_001',
    date: '2026-01-25',
    payee: 'Payroll - Week 2',
    description: 'Employee payroll disbursement',
    type: 'check',
    amount: -7600,
    checkNumber: '1006',
    category: 'Salaries',
    accountId: 'acc_025',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'CHK-1006',
  },
  {
    txId: 'btx_010',
    bankAccountId: 'bank_001',
    date: '2026-01-28',
    payee: 'Bright Ideas Marketing',
    description: 'January social media campaign',
    type: 'check',
    amount: -1200,
    checkNumber: '1007',
    category: 'Marketing',
    accountId: 'acc_029',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'CHK-1007',
  },
  {
    txId: 'btx_011',
    bankAccountId: 'bank_001',
    date: '2026-01-31',
    payee: 'First National Bank',
    description: 'Monthly account maintenance fee',
    type: 'fee',
    amount: -25,
    checkNumber: null,
    category: 'Bank Fees',
    accountId: 'acc_034',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'FEE-4001',
  },
  {
    txId: 'btx_012',
    bankAccountId: 'bank_001',
    date: '2026-02-03',
    payee: 'ABC Property Management',
    description: 'February office rent',
    type: 'check',
    amount: -4500,
    checkNumber: '1008',
    category: 'Rent',
    accountId: 'acc_023',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'CHK-1008',
  },
  {
    txId: 'btx_013',
    bankAccountId: 'bank_001',
    date: '2026-02-05',
    payee: 'Smith & Associates',
    description: 'Legal consulting retainer',
    type: 'check',
    amount: -1500,
    checkNumber: '1009',
    category: 'Professional Fees',
    accountId: 'acc_031',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'CHK-1009',
  },
  {
    txId: 'btx_014',
    bankAccountId: 'bank_001',
    date: '2026-02-07',
    payee: 'Widget Corp',
    description: 'Invoice #INV-004 payment received',
    type: 'deposit',
    amount: 12750,
    checkNumber: null,
    category: 'Sales Revenue',
    accountId: 'acc_017',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'DEP-2003',
  },
  {
    txId: 'btx_015',
    bankAccountId: 'bank_001',
    date: '2026-02-10',
    payee: 'Payroll - Week 3',
    description: 'Employee payroll disbursement',
    type: 'check',
    amount: -7600,
    checkNumber: '1010',
    category: 'Salaries',
    accountId: 'acc_025',
    isCleared: true,
    isReconciled: false,
    referenceNumber: 'CHK-1010',
  },
  {
    txId: 'btx_016',
    bankAccountId: 'bank_001',
    date: '2026-02-12',
    payee: 'SafeGuard Insurance',
    description: 'Quarterly business insurance premium',
    type: 'check',
    amount: -1550,
    checkNumber: '1011',
    category: 'Insurance',
    accountId: 'acc_027',
    isCleared: true,
    isReconciled: false,
    referenceNumber: 'CHK-1011',
  },
  {
    txId: 'btx_017',
    bankAccountId: 'bank_001',
    date: '2026-02-15',
    payee: 'Metro Water Authority',
    description: 'February water & sewer bill',
    type: 'check',
    amount: -180,
    checkNumber: '1012',
    category: 'Utilities',
    accountId: 'acc_024',
    isCleared: true,
    isReconciled: false,
    referenceNumber: 'CHK-1012',
  },
  {
    txId: 'btx_018',
    bankAccountId: 'bank_001',
    date: '2026-02-18',
    payee: 'DataStream Solutions',
    description: 'IT support services payment',
    type: 'deposit',
    amount: 3400,
    checkNumber: null,
    category: 'Service Revenue',
    accountId: 'acc_018',
    isCleared: true,
    isReconciled: false,
    referenceNumber: 'DEP-2004',
  },
  {
    txId: 'btx_019',
    bankAccountId: 'bank_001',
    date: '2026-02-20',
    payee: 'Transfer to Savings',
    description: 'Monthly savings transfer',
    type: 'transfer',
    amount: -2000,
    checkNumber: null,
    category: 'Transfer',
    accountId: 'acc_003',
    isCleared: true,
    isReconciled: false,
    referenceNumber: 'TRF-3002',
  },
  {
    txId: 'btx_020',
    bankAccountId: 'bank_001',
    date: '2026-02-22',
    payee: 'Payroll - Week 4',
    description: 'Employee payroll disbursement',
    type: 'check',
    amount: -7600,
    checkNumber: '1013',
    category: 'Salaries',
    accountId: 'acc_025',
    isCleared: true,
    isReconciled: false,
    referenceNumber: 'CHK-1013',
  },
  {
    txId: 'btx_021',
    bankAccountId: 'bank_001',
    date: '2026-02-25',
    payee: 'Horizon Logistics',
    description: 'Shipping & delivery services',
    type: 'check',
    amount: -890,
    checkNumber: '1014',
    category: 'Delivery',
    accountId: 'acc_032',
    isCleared: true,
    isReconciled: false,
    referenceNumber: 'CHK-1014',
  },
  {
    txId: 'btx_022',
    bankAccountId: 'bank_001',
    date: '2026-02-28',
    payee: 'First National Bank',
    description: 'Monthly account maintenance fee',
    type: 'fee',
    amount: -25,
    checkNumber: null,
    category: 'Bank Fees',
    accountId: 'acc_034',
    isCleared: true,
    isReconciled: false,
    referenceNumber: 'FEE-4002',
  },
  {
    txId: 'btx_023',
    bankAccountId: 'bank_001',
    date: '2026-03-01',
    payee: 'ABC Property Management',
    description: 'March office rent',
    type: 'check',
    amount: -4500,
    checkNumber: '1015',
    category: 'Rent',
    accountId: 'acc_023',
    isCleared: false,
    isReconciled: false,
    referenceNumber: 'CHK-1015',
  },
  {
    txId: 'btx_024',
    bankAccountId: 'bank_001',
    date: '2026-03-02',
    payee: 'NovaTech Industries',
    description: 'Product sales deposit',
    type: 'deposit',
    amount: 6800,
    checkNumber: null,
    category: 'Sales Revenue',
    accountId: 'acc_017',
    isCleared: false,
    isReconciled: false,
    referenceNumber: 'DEP-2005',
  },
  {
    txId: 'btx_025',
    bankAccountId: 'bank_001',
    date: '2026-03-02',
    payee: 'BuildRight Materials',
    description: 'Construction supplies purchase',
    type: 'check',
    amount: -3200,
    checkNumber: '1016',
    category: 'Cost of Goods Sold',
    accountId: 'acc_021',
    isCleared: false,
    isReconciled: false,
    referenceNumber: 'CHK-1016',
  },
  {
    txId: 'btx_026',
    bankAccountId: 'bank_001',
    date: '2026-03-03',
    payee: 'Payroll - Week 5',
    description: 'Employee payroll disbursement',
    type: 'check',
    amount: -7600,
    checkNumber: '1017',
    category: 'Salaries',
    accountId: 'acc_025',
    isCleared: false,
    isReconciled: false,
    referenceNumber: 'CHK-1017',
  },
  {
    txId: 'btx_027',
    bankAccountId: 'bank_001',
    date: '2026-03-03',
    payee: 'Bright Ideas Marketing',
    description: 'March marketing campaign',
    type: 'check',
    amount: -1500,
    checkNumber: '1018',
    category: 'Marketing',
    accountId: 'acc_029',
    isCleared: false,
    isReconciled: false,
    referenceNumber: 'CHK-1018',
  },
  {
    txId: 'btx_028',
    bankAccountId: 'bank_001',
    date: '2026-03-03',
    payee: 'FastCourier Express',
    description: 'Expedited shipping charges',
    type: 'check',
    amount: -420,
    checkNumber: '1019',
    category: 'Delivery',
    accountId: 'acc_032',
    isCleared: false,
    isReconciled: false,
    referenceNumber: 'CHK-1019',
  },

  // ─── BUSINESS SAVINGS (bank_002) ── 10 transactions ──────
  {
    txId: 'btx_029',
    bankAccountId: 'bank_002',
    date: '2026-01-02',
    payee: 'First National Bank',
    description: 'Opening balance deposit',
    type: 'deposit',
    amount: 10000,
    checkNumber: null,
    category: 'Transfer',
    accountId: 'acc_002',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'DEP-5001',
  },
  {
    txId: 'btx_030',
    bankAccountId: 'bank_002',
    date: '2026-01-20',
    payee: 'Transfer from Checking',
    description: 'Monthly savings transfer',
    type: 'transfer',
    amount: 3000,
    checkNumber: null,
    category: 'Transfer',
    accountId: 'acc_002',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'TRF-3001',
  },
  {
    txId: 'btx_031',
    bankAccountId: 'bank_002',
    date: '2026-01-31',
    payee: 'First National Bank',
    description: 'January interest earned',
    type: 'interest',
    amount: 18.75,
    checkNumber: null,
    category: 'Interest Income',
    accountId: 'acc_019',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'INT-6001',
  },
  {
    txId: 'btx_032',
    bankAccountId: 'bank_002',
    date: '2026-02-15',
    payee: 'Emergency Fund Transfer',
    description: 'Withdrawal for equipment repair',
    type: 'transfer',
    amount: -1500,
    checkNumber: null,
    category: 'Transfer',
    accountId: 'acc_002',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'TRF-3003',
  },
  {
    txId: 'btx_033',
    bankAccountId: 'bank_002',
    date: '2026-02-20',
    payee: 'Transfer from Checking',
    description: 'Monthly savings transfer',
    type: 'transfer',
    amount: 2000,
    checkNumber: null,
    category: 'Transfer',
    accountId: 'acc_002',
    isCleared: true,
    isReconciled: false,
    referenceNumber: 'TRF-3002',
  },
  {
    txId: 'btx_034',
    bankAccountId: 'bank_002',
    date: '2026-02-28',
    payee: 'First National Bank',
    description: 'February interest earned',
    type: 'interest',
    amount: 21.50,
    checkNumber: null,
    category: 'Interest Income',
    accountId: 'acc_019',
    isCleared: true,
    isReconciled: false,
    referenceNumber: 'INT-6002',
  },
  {
    txId: 'btx_035',
    bankAccountId: 'bank_002',
    date: '2026-02-28',
    payee: 'First National Bank',
    description: 'Monthly savings maintenance fee',
    type: 'fee',
    amount: -5,
    checkNumber: null,
    category: 'Bank Fees',
    accountId: 'acc_034',
    isCleared: true,
    isReconciled: false,
    referenceNumber: 'FEE-4003',
  },
  {
    txId: 'btx_036',
    bankAccountId: 'bank_002',
    date: '2026-03-01',
    payee: 'Bonus deposit',
    description: 'Year-end bonus reserve',
    type: 'deposit',
    amount: 1500,
    checkNumber: null,
    category: 'Transfer',
    accountId: 'acc_002',
    isCleared: false,
    isReconciled: false,
    referenceNumber: 'DEP-5002',
  },
  {
    txId: 'btx_037',
    bankAccountId: 'bank_002',
    date: '2026-03-02',
    payee: 'First National Bank',
    description: 'March interest (projected)',
    type: 'interest',
    amount: 19.25,
    checkNumber: null,
    category: 'Interest Income',
    accountId: 'acc_019',
    isCleared: false,
    isReconciled: false,
    referenceNumber: 'INT-6003',
  },
  {
    txId: 'btx_038',
    bankAccountId: 'bank_002',
    date: '2026-03-03',
    payee: 'CD Maturity',
    description: 'Short-term CD matured and deposited',
    type: 'deposit',
    amount: 500,
    checkNumber: null,
    category: 'Interest Income',
    accountId: 'acc_019',
    isCleared: false,
    isReconciled: false,
    referenceNumber: 'DEP-5003',
  },

  // ─── BUSINESS CREDIT CARD (bank_003) ── 12 transactions ──
  {
    txId: 'btx_039',
    bankAccountId: 'bank_003',
    date: '2026-01-03',
    payee: 'Amazon Business',
    description: 'Office supplies & printer paper',
    type: 'card_charge',
    amount: -145.99,
    checkNumber: null,
    category: 'Office Supplies',
    accountId: 'acc_026',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'CC-7001',
  },
  {
    txId: 'btx_040',
    bankAccountId: 'bank_003',
    date: '2026-01-10',
    payee: 'Delta Airlines',
    description: 'Business travel - NY conference',
    type: 'card_charge',
    amount: -485.00,
    checkNumber: null,
    category: 'Travel',
    accountId: 'acc_030',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'CC-7002',
  },
  {
    txId: 'btx_041',
    bankAccountId: 'bank_003',
    date: '2026-01-15',
    payee: 'Hilton Hotels',
    description: 'Hotel accommodation - NY conference',
    type: 'card_charge',
    amount: -312.50,
    checkNumber: null,
    category: 'Travel',
    accountId: 'acc_030',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'CC-7003',
  },
  {
    txId: 'btx_042',
    bankAccountId: 'bank_003',
    date: '2026-01-20',
    payee: 'Google Ads',
    description: 'January PPC campaign charges',
    type: 'card_charge',
    amount: -420.00,
    checkNumber: null,
    category: 'Marketing',
    accountId: 'acc_029',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'CC-7004',
  },
  {
    txId: 'btx_043',
    bankAccountId: 'bank_003',
    date: '2026-01-25',
    payee: 'Credit Card Payment',
    description: 'Payment from checking account',
    type: 'deposit',
    amount: 1500,
    checkNumber: null,
    category: 'Transfer',
    accountId: 'acc_002',
    isCleared: true,
    isReconciled: true,
    referenceNumber: 'PMT-8001',
  },
  {
    txId: 'btx_044',
    bankAccountId: 'bank_003',
    date: '2026-02-01',
    payee: 'Zoom Communications',
    description: 'Monthly video conferencing subscription',
    type: 'card_charge',
    amount: -49.99,
    checkNumber: null,
    category: 'Utilities',
    accountId: 'acc_024',
    isCleared: true,
    isReconciled: false,
    referenceNumber: 'CC-7005',
  },
  {
    txId: 'btx_045',
    bankAccountId: 'bank_003',
    date: '2026-02-05',
    payee: 'Staples',
    description: 'Toner cartridges and binders',
    type: 'card_charge',
    amount: -89.50,
    checkNumber: null,
    category: 'Office Supplies',
    accountId: 'acc_026',
    isCleared: true,
    isReconciled: false,
    referenceNumber: 'CC-7006',
  },
  {
    txId: 'btx_046',
    bankAccountId: 'bank_003',
    date: '2026-02-12',
    payee: 'Facebook Ads',
    description: 'February social media ads',
    type: 'card_charge',
    amount: -350.00,
    checkNumber: null,
    category: 'Marketing',
    accountId: 'acc_029',
    isCleared: true,
    isReconciled: false,
    referenceNumber: 'CC-7007',
  },
  {
    txId: 'btx_047',
    bankAccountId: 'bank_003',
    date: '2026-02-20',
    payee: 'Credit Card Payment',
    description: 'Payment from checking account',
    type: 'deposit',
    amount: 1200,
    checkNumber: null,
    category: 'Transfer',
    accountId: 'acc_002',
    isCleared: true,
    isReconciled: false,
    referenceNumber: 'PMT-8002',
  },
  {
    txId: 'btx_048',
    bankAccountId: 'bank_003',
    date: '2026-02-28',
    payee: 'Chase Bank',
    description: 'Monthly interest charge',
    type: 'fee',
    amount: -38.75,
    checkNumber: null,
    category: 'Interest Expense',
    accountId: 'acc_033',
    isCleared: true,
    isReconciled: false,
    referenceNumber: 'INT-9001',
  },
  {
    txId: 'btx_049',
    bankAccountId: 'bank_003',
    date: '2026-03-01',
    payee: 'Uber for Business',
    description: 'Client transportation charges',
    type: 'card_charge',
    amount: -67.40,
    checkNumber: null,
    category: 'Travel',
    accountId: 'acc_030',
    isCleared: false,
    isReconciled: false,
    referenceNumber: 'CC-7008',
  },
  {
    txId: 'btx_050',
    bankAccountId: 'bank_003',
    date: '2026-03-02',
    payee: 'Microsoft 365',
    description: 'Annual software subscription renewal',
    type: 'card_charge',
    amount: -299.99,
    checkNumber: null,
    category: 'Office Supplies',
    accountId: 'acc_026',
    isCleared: false,
    isReconciled: false,
    referenceNumber: 'CC-7009',
  },
];
