// ============================================================
// FINMATRIX - Chart of Accounts Dummy Data
// ============================================================

export interface Account {
  accountId: string;
  companyId: string;
  accountNumber: string;
  name: string;
  type: 'asset' | 'liability' | 'equity' | 'revenue' | 'expense';
  subType: string;
  parentAccountId: string | null;
  description: string;
  isActive: boolean;
  openingBalance: number;
  currentBalance: number;
}

export const chartOfAccounts: Account[] = [
  // ─── ASSETS ──────────────────────────────────────────────
  {
    accountId: 'acc_001',
    companyId: 'company_1',
    accountNumber: '1000',
    name: 'Cash',
    type: 'asset',
    subType: 'Current Asset',
    parentAccountId: null,
    description: 'Cash on hand and in registers',
    isActive: true,
    openingBalance: 15000,
    currentBalance: 18420,
  },
  {
    accountId: 'acc_002',
    companyId: 'company_1',
    accountNumber: '1010',
    name: 'Checking Account',
    type: 'asset',
    subType: 'Current Asset',
    parentAccountId: null,
    description: 'Primary business checking account',
    isActive: true,
    openingBalance: 42000,
    currentBalance: 34200,
  },
  {
    accountId: 'acc_003',
    companyId: 'company_1',
    accountNumber: '1020',
    name: 'Savings Account',
    type: 'asset',
    subType: 'Current Asset',
    parentAccountId: null,
    description: 'Business savings account',
    isActive: true,
    openingBalance: 25000,
    currentBalance: 25750,
  },
  {
    accountId: 'acc_004',
    companyId: 'company_1',
    accountNumber: '1100',
    name: 'Accounts Receivable',
    type: 'asset',
    subType: 'Current Asset',
    parentAccountId: null,
    description: 'Amounts owed by customers',
    isActive: true,
    openingBalance: 28500,
    currentBalance: 15780,
  },
  {
    accountId: 'acc_005',
    companyId: 'company_1',
    accountNumber: '1200',
    name: 'Inventory',
    type: 'asset',
    subType: 'Current Asset',
    parentAccountId: null,
    description: 'Merchandise and raw materials in stock',
    isActive: true,
    openingBalance: 65000,
    currentBalance: 72350,
  },
  {
    accountId: 'acc_006',
    companyId: 'company_1',
    accountNumber: '1300',
    name: 'Prepaid Expenses',
    type: 'asset',
    subType: 'Current Asset',
    parentAccountId: null,
    description: 'Expenses paid in advance (insurance, rent)',
    isActive: true,
    openingBalance: 4800,
    currentBalance: 3200,
  },
  {
    accountId: 'acc_007',
    companyId: 'company_1',
    accountNumber: '1500',
    name: 'Equipment',
    type: 'asset',
    subType: 'Fixed Asset',
    parentAccountId: null,
    description: 'Office and warehouse equipment',
    isActive: true,
    openingBalance: 45000,
    currentBalance: 45000,
  },
  {
    accountId: 'acc_008',
    companyId: 'company_1',
    accountNumber: '1510',
    name: 'Accumulated Depreciation',
    type: 'asset',
    subType: 'Fixed Asset',
    parentAccountId: 'acc_007',
    description: 'Total depreciation on equipment',
    isActive: true,
    openingBalance: -9000,
    currentBalance: -12750,
  },

  // ─── LIABILITIES ─────────────────────────────────────────
  {
    accountId: 'acc_009',
    companyId: 'company_1',
    accountNumber: '2000',
    name: 'Accounts Payable',
    type: 'liability',
    subType: 'Current Liability',
    parentAccountId: null,
    description: 'Amounts owed to suppliers and vendors',
    isActive: true,
    openingBalance: 18200,
    currentBalance: 14560,
  },
  {
    accountId: 'acc_010',
    companyId: 'company_1',
    accountNumber: '2100',
    name: 'Credit Card Payable',
    type: 'liability',
    subType: 'Current Liability',
    parentAccountId: null,
    description: 'Outstanding credit card balances',
    isActive: true,
    openingBalance: 5400,
    currentBalance: 3820,
  },
  {
    accountId: 'acc_011',
    companyId: 'company_1',
    accountNumber: '2200',
    name: 'Payroll Liabilities',
    type: 'liability',
    subType: 'Current Liability',
    parentAccountId: null,
    description: 'Wages, taxes, and benefits payable',
    isActive: true,
    openingBalance: 8600,
    currentBalance: 11240,
  },
  {
    accountId: 'acc_012',
    companyId: 'company_1',
    accountNumber: '2300',
    name: 'Sales Tax Payable',
    type: 'liability',
    subType: 'Current Liability',
    parentAccountId: null,
    description: 'Collected sales tax to be remitted',
    isActive: true,
    openingBalance: 2100,
    currentBalance: 3450,
  },
  {
    accountId: 'acc_013',
    companyId: 'company_1',
    accountNumber: '2500',
    name: 'Notes Payable',
    type: 'liability',
    subType: 'Long-term Liability',
    parentAccountId: null,
    description: 'Loan and note obligations',
    isActive: true,
    openingBalance: 50000,
    currentBalance: 42000,
  },

  // ─── EQUITY ──────────────────────────────────────────────
  {
    accountId: 'acc_014',
    companyId: 'company_1',
    accountNumber: '3000',
    name: "Owner's Equity",
    type: 'equity',
    subType: 'Owner Equity',
    parentAccountId: null,
    description: "Owner's capital investment in the business",
    isActive: true,
    openingBalance: 100000,
    currentBalance: 100000,
  },
  {
    accountId: 'acc_015',
    companyId: 'company_1',
    accountNumber: '3100',
    name: 'Retained Earnings',
    type: 'equity',
    subType: 'Owner Equity',
    parentAccountId: null,
    description: 'Accumulated profits retained in the business',
    isActive: true,
    openingBalance: 34500,
    currentBalance: 48720,
  },
  {
    accountId: 'acc_016',
    companyId: 'company_1',
    accountNumber: '3200',
    name: "Owner's Draws",
    type: 'equity',
    subType: 'Owner Equity',
    parentAccountId: null,
    description: 'Withdrawals made by the owner',
    isActive: true,
    openingBalance: 0,
    currentBalance: -8500,
  },

  // ─── REVENUE ─────────────────────────────────────────────
  {
    accountId: 'acc_017',
    companyId: 'company_1',
    accountNumber: '4000',
    name: 'Sales Revenue',
    type: 'revenue',
    subType: 'Operating Revenue',
    parentAccountId: null,
    description: 'Revenue from product sales',
    isActive: true,
    openingBalance: 0,
    currentBalance: 148520,
  },
  {
    accountId: 'acc_018',
    companyId: 'company_1',
    accountNumber: '4100',
    name: 'Service Revenue',
    type: 'revenue',
    subType: 'Operating Revenue',
    parentAccountId: null,
    description: 'Revenue from services rendered',
    isActive: true,
    openingBalance: 0,
    currentBalance: 32400,
  },
  {
    accountId: 'acc_019',
    companyId: 'company_1',
    accountNumber: '4200',
    name: 'Interest Income',
    type: 'revenue',
    subType: 'Other Income',
    parentAccountId: null,
    description: 'Interest earned on bank accounts',
    isActive: true,
    openingBalance: 0,
    currentBalance: 1250,
  },
  {
    accountId: 'acc_020',
    companyId: 'company_1',
    accountNumber: '4300',
    name: 'Other Income',
    type: 'revenue',
    subType: 'Other Income',
    parentAccountId: null,
    description: 'Miscellaneous income sources',
    isActive: false,
    openingBalance: 0,
    currentBalance: 680,
  },

  // ─── EXPENSES ────────────────────────────────────────────
  {
    accountId: 'acc_021',
    companyId: 'company_1',
    accountNumber: '5000',
    name: 'Cost of Goods Sold',
    type: 'expense',
    subType: 'Direct Cost',
    parentAccountId: null,
    description: 'Direct cost of products sold',
    isActive: true,
    openingBalance: 0,
    currentBalance: 62340,
  },
  {
    accountId: 'acc_022',
    companyId: 'company_1',
    accountNumber: '5100',
    name: 'Purchase Discounts',
    type: 'expense',
    subType: 'Direct Cost',
    parentAccountId: null,
    description: 'Discounts received on purchases',
    isActive: true,
    openingBalance: 0,
    currentBalance: -1820,
  },
  {
    accountId: 'acc_023',
    companyId: 'company_1',
    accountNumber: '6000',
    name: 'Rent Expense',
    type: 'expense',
    subType: 'Operating Expense',
    parentAccountId: null,
    description: 'Office and warehouse rent',
    isActive: true,
    openingBalance: 0,
    currentBalance: 18000,
  },
  {
    accountId: 'acc_024',
    companyId: 'company_1',
    accountNumber: '6100',
    name: 'Utilities Expense',
    type: 'expense',
    subType: 'Operating Expense',
    parentAccountId: null,
    description: 'Electricity, water, internet, phone',
    isActive: true,
    openingBalance: 0,
    currentBalance: 4320,
  },
  {
    accountId: 'acc_025',
    companyId: 'company_1',
    accountNumber: '6200',
    name: 'Salaries Expense',
    type: 'expense',
    subType: 'Operating Expense',
    parentAccountId: null,
    description: 'Employee salaries and wages',
    isActive: true,
    openingBalance: 0,
    currentBalance: 86400,
  },
  {
    accountId: 'acc_026',
    companyId: 'company_1',
    accountNumber: '6300',
    name: 'Office Supplies',
    type: 'expense',
    subType: 'Operating Expense',
    parentAccountId: null,
    description: 'Office supplies and stationery',
    isActive: true,
    openingBalance: 0,
    currentBalance: 2150,
  },
  {
    accountId: 'acc_027',
    companyId: 'company_1',
    accountNumber: '6400',
    name: 'Insurance Expense',
    type: 'expense',
    subType: 'Operating Expense',
    parentAccountId: null,
    description: 'Business insurance premiums',
    isActive: true,
    openingBalance: 0,
    currentBalance: 6200,
  },
  {
    accountId: 'acc_028',
    companyId: 'company_1',
    accountNumber: '6500',
    name: 'Depreciation Expense',
    type: 'expense',
    subType: 'Operating Expense',
    parentAccountId: null,
    description: 'Monthly depreciation of fixed assets',
    isActive: true,
    openingBalance: 0,
    currentBalance: 3750,
  },
  {
    accountId: 'acc_029',
    companyId: 'company_1',
    accountNumber: '6600',
    name: 'Marketing Expense',
    type: 'expense',
    subType: 'Operating Expense',
    parentAccountId: null,
    description: 'Advertising and promotional costs',
    isActive: true,
    openingBalance: 0,
    currentBalance: 8900,
  },
  {
    accountId: 'acc_030',
    companyId: 'company_1',
    accountNumber: '6700',
    name: 'Travel Expense',
    type: 'expense',
    subType: 'Operating Expense',
    parentAccountId: null,
    description: 'Business travel and transportation',
    isActive: true,
    openingBalance: 0,
    currentBalance: 3420,
  },
  {
    accountId: 'acc_031',
    companyId: 'company_1',
    accountNumber: '6800',
    name: 'Professional Fees',
    type: 'expense',
    subType: 'Operating Expense',
    parentAccountId: null,
    description: 'Legal, accounting, and consulting fees',
    isActive: true,
    openingBalance: 0,
    currentBalance: 5600,
  },
  {
    accountId: 'acc_032',
    companyId: 'company_1',
    accountNumber: '6900',
    name: 'Delivery Expenses',
    type: 'expense',
    subType: 'Operating Expense',
    parentAccountId: null,
    description: 'Shipping and delivery costs',
    isActive: true,
    openingBalance: 0,
    currentBalance: 7850,
  },
  {
    accountId: 'acc_033',
    companyId: 'company_1',
    accountNumber: '7000',
    name: 'Interest Expense',
    type: 'expense',
    subType: 'Other Expense',
    parentAccountId: null,
    description: 'Interest on loans and notes payable',
    isActive: true,
    openingBalance: 0,
    currentBalance: 2400,
  },
  {
    accountId: 'acc_034',
    companyId: 'company_1',
    accountNumber: '7100',
    name: 'Bank Fees',
    type: 'expense',
    subType: 'Other Expense',
    parentAccountId: null,
    description: 'Bank service charges and fees',
    isActive: false,
    openingBalance: 0,
    currentBalance: 380,
  },
  {
    accountId: 'acc_035',
    companyId: 'company_1',
    accountNumber: '7200',
    name: 'Miscellaneous Expense',
    type: 'expense',
    subType: 'Other Expense',
    parentAccountId: null,
    description: 'Uncategorized business expenses',
    isActive: true,
    openingBalance: 0,
    currentBalance: 450,
  },
];
