// ============================================================
// FINMATRIX - Inventory Items Dummy Data  (30 items)
// ============================================================

export type Category =
  | 'Electronics'
  | 'Office Supplies'
  | 'Furniture'
  | 'Raw Materials'
  | 'Finished Goods';

export type UnitOfMeasure = 'each' | 'box' | 'kg' | 'liter' | 'set';

export type LocationId = 'warehouse_1' | 'warehouse_2' | 'store_1';

export interface InventoryItem {
  itemId: string;
  companyId: string;
  sku: string;
  name: string;
  description: string;
  category: Category;
  unitOfMeasure: UnitOfMeasure;
  costMethod: 'average';
  unitCost: number;
  sellingPrice: number;
  quantityOnHand: number;
  quantityOnOrder: number;
  quantityCommitted: number;
  reorderPoint: number;
  reorderQuantity: number;
  minStock: number;
  maxStock: number;
  isActive: boolean;
  serialTracking: boolean;
  lotTracking: boolean;
  barcodeData: string | null;
  locationId: LocationId;
  imageUrl: null;
  lastUpdated: string;
  sourceAgencyId?: string;
}

// ── Stock level distribution ────────────────────────────────
// 10 well-stocked  (qty > reorderPoint by comfortable margin)
//  8 at/near reorder  (qty ≈ reorderPoint)
//  6 below minimum  (qty < minStock)
//  4 at zero  (qty = 0)
//  2 inactive  (isActive = false)
// ─────────────────────────────────────────────────────────────

export const inventoryItems: InventoryItem[] = [
  // ═══ ELECTRONICS (6) ══════════════════════════════════════
  {
    itemId: 'inv_001',
    companyId: 'comp_001',
    sku: 'SKU-001',
    name: 'Wireless Bluetooth Mouse',
    description: 'Ergonomic wireless mouse with Bluetooth 5.0 and USB-C charging',
    category: 'Electronics',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 12.50,
    sellingPrice: 24.99,
    quantityOnHand: 150,
    quantityOnOrder: 0,
    quantityCommitted: 8,
    reorderPoint: 30,
    reorderQuantity: 100,
    minStock: 20,
    maxStock: 300,
    isActive: true,
    serialTracking: true,
    lotTracking: false,
    barcodeData: '8901234567890',
    locationId: 'warehouse_1',
    imageUrl: null,
    lastUpdated: '2026-02-28T10:30:00Z',
  },
  {
    itemId: 'inv_002',
    companyId: 'comp_001',
    sku: 'SKU-002',
    name: 'USB-C Hub 7-in-1',
    description: 'Multi-port USB-C hub with HDMI, SD card, USB 3.0 ports',
    category: 'Electronics',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 18.75,
    sellingPrice: 39.99,
    quantityOnHand: 85,
    quantityOnOrder: 50,
    quantityCommitted: 12,
    reorderPoint: 25,
    reorderQuantity: 75,
    minStock: 15,
    maxStock: 200,
    isActive: true,
    serialTracking: true,
    lotTracking: false,
    barcodeData: '8901234567891',
    locationId: 'warehouse_1',
    imageUrl: null,
    lastUpdated: '2026-02-27T14:15:00Z',
  },
  {
    itemId: 'inv_003',
    companyId: 'comp_001',
    sku: 'SKU-003',
    name: 'Noise-Cancelling Headphones',
    description: 'Over-ear ANC headphones with 30hr battery and mic',
    category: 'Electronics',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 45.00,
    sellingPrice: 89.99,
    quantityOnHand: 25,
    quantityOnOrder: 0,
    quantityCommitted: 3,
    reorderPoint: 25,
    reorderQuantity: 50,
    minStock: 15,
    maxStock: 150,
    isActive: true,
    serialTracking: true,
    lotTracking: false,
    barcodeData: '8901234567892',
    locationId: 'warehouse_2',
    imageUrl: null,
    lastUpdated: '2026-02-25T09:00:00Z',
  },
  {
    itemId: 'inv_004',
    companyId: 'comp_001',
    sku: 'SKU-004',
    name: 'Webcam HD 1080p',
    description: 'Full HD webcam with auto-focus and built-in ring light',
    category: 'Electronics',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 22.00,
    sellingPrice: 49.99,
    quantityOnHand: 5,
    quantityOnOrder: 40,
    quantityCommitted: 2,
    reorderPoint: 15,
    reorderQuantity: 40,
    minStock: 10,
    maxStock: 120,
    isActive: true,
    serialTracking: true,
    lotTracking: false,
    barcodeData: '8901234567893',
    locationId: 'warehouse_1',
    imageUrl: null,
    lastUpdated: '2026-02-20T16:45:00Z',
  },
  {
    itemId: 'inv_005',
    companyId: 'comp_001',
    sku: 'SKU-005',
    name: 'Portable Charger 20000mAh',
    description: 'High-capacity power bank with dual USB-C and LCD display',
    category: 'Electronics',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 15.00,
    sellingPrice: 34.99,
    quantityOnHand: 0,
    quantityOnOrder: 60,
    quantityCommitted: 0,
    reorderPoint: 20,
    reorderQuantity: 60,
    minStock: 10,
    maxStock: 200,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567894',
    locationId: 'warehouse_2',
    imageUrl: null,
    lastUpdated: '2026-02-18T11:00:00Z',
  },
  {
    itemId: 'inv_006',
    companyId: 'comp_001',
    sku: 'SKU-006',
    name: 'Mechanical Keyboard',
    description: 'Compact RGB mechanical keyboard with hot-swap switches',
    category: 'Electronics',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 35.00,
    sellingPrice: 74.99,
    quantityOnHand: 0,
    quantityOnOrder: 0,
    quantityCommitted: 0,
    reorderPoint: 15,
    reorderQuantity: 40,
    minStock: 10,
    maxStock: 100,
    isActive: false,
    serialTracking: true,
    lotTracking: false,
    barcodeData: '8901234567895',
    locationId: 'warehouse_1',
    imageUrl: null,
    lastUpdated: '2026-01-15T08:30:00Z',
  },

  // ═══ OFFICE SUPPLIES (6) ══════════════════════════════════
  {
    itemId: 'inv_007',
    companyId: 'comp_001',
    sku: 'SKU-007',
    name: 'Premium Copy Paper A4',
    description: '80gsm bright white multi-purpose copy paper, 500 sheets',
    category: 'Office Supplies',
    unitOfMeasure: 'box',
    costMethod: 'average',
    unitCost: 4.25,
    sellingPrice: 8.99,
    quantityOnHand: 320,
    quantityOnOrder: 0,
    quantityCommitted: 45,
    reorderPoint: 100,
    reorderQuantity: 250,
    minStock: 60,
    maxStock: 600,
    isActive: true,
    serialTracking: false,
    lotTracking: true,
    barcodeData: '8901234567896',
    locationId: 'warehouse_1',
    imageUrl: null,
    lastUpdated: '2026-03-01T08:00:00Z',
  },
  {
    itemId: 'inv_008',
    companyId: 'comp_001',
    sku: 'SKU-008',
    name: 'Gel Pen Set (12-Pack)',
    description: 'Smooth gel pens in assorted colors, 0.7mm tip',
    category: 'Office Supplies',
    unitOfMeasure: 'set',
    costMethod: 'average',
    unitCost: 3.50,
    sellingPrice: 7.99,
    quantityOnHand: 200,
    quantityOnOrder: 0,
    quantityCommitted: 18,
    reorderPoint: 50,
    reorderQuantity: 150,
    minStock: 30,
    maxStock: 400,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567897',
    locationId: 'store_1',
    imageUrl: null,
    lastUpdated: '2026-02-28T12:00:00Z',
  },
  {
    itemId: 'inv_009',
    companyId: 'comp_001',
    sku: 'SKU-009',
    name: 'Sticky Notes (3x3) 12-Pack',
    description: 'Self-adhesive repositionable notes, assorted neon colors',
    category: 'Office Supplies',
    unitOfMeasure: 'box',
    costMethod: 'average',
    unitCost: 2.80,
    sellingPrice: 5.99,
    quantityOnHand: 50,
    quantityOnOrder: 0,
    quantityCommitted: 5,
    reorderPoint: 50,
    reorderQuantity: 100,
    minStock: 30,
    maxStock: 300,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567898',
    locationId: 'store_1',
    imageUrl: null,
    lastUpdated: '2026-02-26T15:30:00Z',
  },
  {
    itemId: 'inv_010',
    companyId: 'comp_001',
    sku: 'SKU-010',
    name: 'Whiteboard Markers (8-Pack)',
    description: 'Dry erase markers with chisel tip, 8 colors',
    category: 'Office Supplies',
    unitOfMeasure: 'set',
    costMethod: 'average',
    unitCost: 5.60,
    sellingPrice: 11.99,
    quantityOnHand: 8,
    quantityOnOrder: 0,
    quantityCommitted: 2,
    reorderPoint: 20,
    reorderQuantity: 60,
    minStock: 15,
    maxStock: 150,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567899',
    locationId: 'store_1',
    imageUrl: null,
    lastUpdated: '2026-02-22T10:00:00Z',
  },
  {
    itemId: 'inv_011',
    companyId: 'comp_001',
    sku: 'SKU-011',
    name: 'Printer Toner Cartridge',
    description: 'Compatible black toner for office laser printers',
    category: 'Office Supplies',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 28.00,
    sellingPrice: 54.99,
    quantityOnHand: 3,
    quantityOnOrder: 10,
    quantityCommitted: 1,
    reorderPoint: 8,
    reorderQuantity: 15,
    minStock: 5,
    maxStock: 40,
    isActive: true,
    serialTracking: false,
    lotTracking: true,
    barcodeData: '8901234567900',
    locationId: 'warehouse_2',
    imageUrl: null,
    lastUpdated: '2026-02-19T17:00:00Z',
  },
  {
    itemId: 'inv_012',
    companyId: 'comp_001',
    sku: 'SKU-012',
    name: 'Binder Clips Assorted',
    description: 'Metal binder clips in small, medium, and large',
    category: 'Office Supplies',
    unitOfMeasure: 'box',
    costMethod: 'average',
    unitCost: 1.75,
    sellingPrice: 3.99,
    quantityOnHand: 0,
    quantityOnOrder: 0,
    quantityCommitted: 0,
    reorderPoint: 30,
    reorderQuantity: 80,
    minStock: 20,
    maxStock: 200,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: null,
    locationId: 'store_1',
    imageUrl: null,
    lastUpdated: '2026-02-10T09:30:00Z',
  },

  // ═══ FURNITURE (6) ════════════════════════════════════════
  {
    itemId: 'inv_013',
    companyId: 'comp_001',
    sku: 'SKU-013',
    name: 'Ergonomic Office Chair',
    description: 'Adjustable lumbar support, mesh back, armrests',
    category: 'Furniture',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 185.00,
    sellingPrice: 349.99,
    quantityOnHand: 22,
    quantityOnOrder: 10,
    quantityCommitted: 4,
    reorderPoint: 8,
    reorderQuantity: 15,
    minStock: 5,
    maxStock: 40,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567901',
    locationId: 'warehouse_1',
    imageUrl: null,
    lastUpdated: '2026-03-01T07:00:00Z',
  },
  {
    itemId: 'inv_014',
    companyId: 'comp_001',
    sku: 'SKU-014',
    name: 'Standing Desk 60"',
    description: 'Electric height-adjustable standing desk, bamboo finish',
    category: 'Furniture',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 280.00,
    sellingPrice: 549.99,
    quantityOnHand: 8,
    quantityOnOrder: 5,
    quantityCommitted: 2,
    reorderPoint: 5,
    reorderQuantity: 10,
    minStock: 3,
    maxStock: 25,
    isActive: true,
    serialTracking: true,
    lotTracking: false,
    barcodeData: '8901234567902',
    locationId: 'warehouse_1',
    imageUrl: null,
    lastUpdated: '2026-02-28T13:00:00Z',
  },
  {
    itemId: 'inv_015',
    companyId: 'comp_001',
    sku: 'SKU-015',
    name: 'Filing Cabinet 3-Drawer',
    description: 'Lockable metal filing cabinet, letter/legal size',
    category: 'Furniture',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 95.00,
    sellingPrice: 189.99,
    quantityOnHand: 5,
    quantityOnOrder: 0,
    quantityCommitted: 1,
    reorderPoint: 5,
    reorderQuantity: 10,
    minStock: 3,
    maxStock: 20,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567903',
    locationId: 'warehouse_2',
    imageUrl: null,
    lastUpdated: '2026-02-24T11:30:00Z',
  },
  {
    itemId: 'inv_016',
    companyId: 'comp_001',
    sku: 'SKU-016',
    name: 'Bookshelf 5-Tier',
    description: 'Modern industrial open bookshelf, wood and metal',
    category: 'Furniture',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 65.00,
    sellingPrice: 129.99,
    quantityOnHand: 2,
    quantityOnOrder: 0,
    quantityCommitted: 0,
    reorderPoint: 4,
    reorderQuantity: 8,
    minStock: 3,
    maxStock: 15,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567904',
    locationId: 'warehouse_2',
    imageUrl: null,
    lastUpdated: '2026-02-21T14:00:00Z',
  },
  {
    itemId: 'inv_017',
    companyId: 'comp_001',
    sku: 'SKU-017',
    name: 'Monitor Stand Riser',
    description: 'Wooden desktop monitor riser with storage drawer',
    category: 'Furniture',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 18.00,
    sellingPrice: 34.99,
    quantityOnHand: 40,
    quantityOnOrder: 0,
    quantityCommitted: 6,
    reorderPoint: 15,
    reorderQuantity: 30,
    minStock: 10,
    maxStock: 80,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: null,
    locationId: 'store_1',
    imageUrl: null,
    lastUpdated: '2026-02-27T09:45:00Z',
  },
  {
    itemId: 'inv_018',
    companyId: 'comp_001',
    sku: 'SKU-018',
    name: 'Conference Table 8-Seat',
    description: 'Oval conference table with cable management',
    category: 'Furniture',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 420.00,
    sellingPrice: 799.99,
    quantityOnHand: 0,
    quantityOnOrder: 2,
    quantityCommitted: 0,
    reorderPoint: 2,
    reorderQuantity: 3,
    minStock: 1,
    maxStock: 8,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567906',
    locationId: 'warehouse_1',
    imageUrl: null,
    lastUpdated: '2026-02-15T16:00:00Z',
  },

  // ═══ RAW MATERIALS (6) ════════════════════════════════════
  {
    itemId: 'inv_019',
    companyId: 'comp_001',
    sku: 'SKU-019',
    name: 'Steel Sheet 4x8ft',
    description: '16-gauge cold-rolled steel sheet for fabrication',
    category: 'Raw Materials',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 48.00,
    sellingPrice: 72.00,
    quantityOnHand: 60,
    quantityOnOrder: 20,
    quantityCommitted: 10,
    reorderPoint: 20,
    reorderQuantity: 40,
    minStock: 15,
    maxStock: 100,
    isActive: true,
    serialTracking: false,
    lotTracking: true,
    barcodeData: '8901234567907',
    locationId: 'warehouse_1',
    imageUrl: null,
    lastUpdated: '2026-03-01T06:00:00Z',
  },
  {
    itemId: 'inv_020',
    companyId: 'comp_001',
    sku: 'SKU-020',
    name: 'Industrial Adhesive',
    description: 'High-strength epoxy adhesive for metal bonding',
    category: 'Raw Materials',
    unitOfMeasure: 'liter',
    costMethod: 'average',
    unitCost: 32.00,
    sellingPrice: 55.00,
    quantityOnHand: 20,
    quantityOnOrder: 0,
    quantityCommitted: 3,
    reorderPoint: 20,
    reorderQuantity: 30,
    minStock: 12,
    maxStock: 60,
    isActive: true,
    serialTracking: false,
    lotTracking: true,
    barcodeData: '8901234567908',
    locationId: 'warehouse_2',
    imageUrl: null,
    lastUpdated: '2026-02-26T07:30:00Z',
  },
  {
    itemId: 'inv_021',
    companyId: 'comp_001',
    sku: 'SKU-021',
    name: 'Copper Wire Spool 14AWG',
    description: 'Solid copper wire for electrical applications, 500ft',
    category: 'Raw Materials',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 85.00,
    sellingPrice: 125.00,
    quantityOnHand: 12,
    quantityOnOrder: 0,
    quantityCommitted: 4,
    reorderPoint: 10,
    reorderQuantity: 20,
    minStock: 8,
    maxStock: 40,
    isActive: true,
    serialTracking: false,
    lotTracking: true,
    barcodeData: '8901234567909',
    locationId: 'warehouse_1',
    imageUrl: null,
    lastUpdated: '2026-02-23T10:00:00Z',
  },
  {
    itemId: 'inv_022',
    companyId: 'comp_001',
    sku: 'SKU-022',
    name: 'Acrylic Resin',
    description: 'Clear casting resin for molds and prototyping',
    category: 'Raw Materials',
    unitOfMeasure: 'kg',
    costMethod: 'average',
    unitCost: 18.50,
    sellingPrice: 32.00,
    quantityOnHand: 7,
    quantityOnOrder: 25,
    quantityCommitted: 0,
    reorderPoint: 15,
    reorderQuantity: 30,
    minStock: 10,
    maxStock: 50,
    isActive: true,
    serialTracking: false,
    lotTracking: true,
    barcodeData: '8901234567910',
    locationId: 'warehouse_2',
    imageUrl: null,
    lastUpdated: '2026-02-18T13:15:00Z',
  },
  {
    itemId: 'inv_023',
    companyId: 'comp_001',
    sku: 'SKU-023',
    name: 'Plywood Sheet 4x8ft',
    description: '3/4 inch birch plywood, cabinet grade',
    category: 'Raw Materials',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 38.00,
    sellingPrice: 58.00,
    quantityOnHand: 35,
    quantityOnOrder: 0,
    quantityCommitted: 8,
    reorderPoint: 15,
    reorderQuantity: 25,
    minStock: 10,
    maxStock: 60,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567911',
    locationId: 'warehouse_1',
    imageUrl: null,
    lastUpdated: '2026-02-25T08:30:00Z',
  },
  {
    itemId: 'inv_024',
    companyId: 'comp_001',
    sku: 'SKU-024',
    name: 'Nylon Fabric Roll',
    description: 'Industrial-grade nylon fabric, 60 inches wide, per yard',
    category: 'Raw Materials',
    unitOfMeasure: 'kg',
    costMethod: 'average',
    unitCost: 12.00,
    sellingPrice: 22.00,
    quantityOnHand: 0,
    quantityOnOrder: 0,
    quantityCommitted: 0,
    reorderPoint: 25,
    reorderQuantity: 50,
    minStock: 15,
    maxStock: 100,
    isActive: false,
    serialTracking: false,
    lotTracking: true,
    barcodeData: null,
    locationId: 'warehouse_2',
    imageUrl: null,
    lastUpdated: '2026-01-10T12:00:00Z',
  },

  // ═══ FINISHED GOODS (6) ═══════════════════════════════════
  {
    itemId: 'inv_025',
    companyId: 'comp_001',
    sku: 'SKU-025',
    name: 'Custom Tool Kit',
    description: 'Assembled professional tool kit - 120 pieces',
    category: 'Finished Goods',
    unitOfMeasure: 'set',
    costMethod: 'average',
    unitCost: 55.00,
    sellingPrice: 109.99,
    quantityOnHand: 45,
    quantityOnOrder: 0,
    quantityCommitted: 7,
    reorderPoint: 15,
    reorderQuantity: 30,
    minStock: 10,
    maxStock: 80,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567913',
    locationId: 'warehouse_1',
    imageUrl: null,
    lastUpdated: '2026-03-02T09:00:00Z',
  },
  {
    itemId: 'inv_026',
    companyId: 'comp_001',
    sku: 'SKU-026',
    name: 'LED Desk Lamp',
    description: 'Dimmable LED lamp with wireless charging base',
    category: 'Finished Goods',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 22.00,
    sellingPrice: 44.99,
    quantityOnHand: 65,
    quantityOnOrder: 0,
    quantityCommitted: 10,
    reorderPoint: 20,
    reorderQuantity: 40,
    minStock: 12,
    maxStock: 120,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567914',
    locationId: 'store_1',
    imageUrl: null,
    lastUpdated: '2026-02-28T11:30:00Z',
  },
  {
    itemId: 'inv_027',
    companyId: 'comp_001',
    sku: 'SKU-027',
    name: 'Wall Clock Modern',
    description: 'Silent sweep wall clock, 12 inch, minimalist design',
    category: 'Finished Goods',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 8.50,
    sellingPrice: 19.99,
    quantityOnHand: 14,
    quantityOnOrder: 30,
    quantityCommitted: 2,
    reorderPoint: 15,
    reorderQuantity: 30,
    minStock: 10,
    maxStock: 60,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567915',
    locationId: 'store_1',
    imageUrl: null,
    lastUpdated: '2026-02-24T08:45:00Z',
  },
  {
    itemId: 'inv_028',
    companyId: 'comp_001',
    sku: 'SKU-028',
    name: 'Whiteboard 48x36',
    description: 'Magnetic dry erase whiteboard with aluminum frame',
    category: 'Finished Goods',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 35.00,
    sellingPrice: 69.99,
    quantityOnHand: 4,
    quantityOnOrder: 0,
    quantityCommitted: 1,
    reorderPoint: 6,
    reorderQuantity: 12,
    minStock: 5,
    maxStock: 25,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567916',
    locationId: 'warehouse_2',
    imageUrl: null,
    lastUpdated: '2026-02-20T14:30:00Z',
  },
  {
    itemId: 'inv_029',
    companyId: 'comp_001',
    sku: 'SKU-029',
    name: 'First Aid Kit Professional',
    description: 'OSHA-compliant 200-piece workplace first aid kit',
    category: 'Finished Goods',
    unitOfMeasure: 'each',
    costMethod: 'average',
    unitCost: 28.00,
    sellingPrice: 54.99,
    quantityOnHand: 10,
    quantityOnOrder: 0,
    quantityCommitted: 1,
    reorderPoint: 10,
    reorderQuantity: 20,
    minStock: 8,
    maxStock: 40,
    isActive: true,
    serialTracking: false,
    lotTracking: true,
    barcodeData: '8901234567917',
    locationId: 'warehouse_1',
    imageUrl: null,
    lastUpdated: '2026-02-22T16:00:00Z',
  },
  {
    itemId: 'inv_030',
    companyId: 'comp_001',
    sku: 'SKU-030',
    name: 'Cable Management Kit',
    description: 'Complete desk cable organizer with clips, sleeves, trays',
    category: 'Finished Goods',
    unitOfMeasure: 'set',
    costMethod: 'average',
    unitCost: 9.00,
    sellingPrice: 19.99,
    quantityOnHand: 90,
    quantityOnOrder: 0,
    quantityCommitted: 15,
    reorderPoint: 25,
    reorderQuantity: 50,
    minStock: 15,
    maxStock: 150,
    isActive: true,
    serialTracking: false,
    lotTracking: false,
    barcodeData: '8901234567918',
    locationId: 'store_1',
    imageUrl: null,
    lastUpdated: '2026-03-01T10:00:00Z',
  },
];
